# Generated by Django 5.0.4 on 2024-04-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]



    operations = [
        migrations.RunSQL('DROP TABLE movies_movie;')
    ]
